# **Chatbot using nlp**

# import libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# load dataset

In [2]:
data = pd.read_csv(r"C:\Users\GCE PMNA\Downloads\supermarket chatbot.csv")
data

,question,response,intent
0,Hello,Hello! Welcome to our supermarket. How can I h...,greeting
1,Bye,Thank you for shopping with us. Have a great day!,goodbye
2,Thanks,You're welcome! Happy to help.,thanks
3,Do you have rice?,"Yes, we have different varieties of rice avail...",product_search
4,Is milk available?,"Yes, milk is currently in stock.",product_availability
...,...,...,...
5995,Show in app category,Displaying in app category,product_category
5996,Find for delivery brand,for delivery products available,brand_search
5997,Change quantity to for shopping,Quantity updated,quantity_update
5998,Deliver to for groceries,Address updated successfully,address_update
5999,Payment issue urgent,Please retry payment,payment_issue

In [3]:
data.isna().sum()

question    0
response    0
intent      0
dtype: int64

In [4]:
data.columns

Index(['question', 'response', 'intent'], dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  6000 non-null   object
 1   response  6000 non-null   object
 2   intent    6000 non-null   object
dtypes: object(3)
memory usage: 140.8+ KB

# Text preprocessing

In [6]:
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\GCE
[nltk_data]     PMNA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\GCE
[nltk_data]     PMNA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to C:\Users\GCE
[nltk_data]     PMNA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [7]:
punctuation = string.punctuation
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

In [8]:
def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    words = nltk.word_tokenize(text)
    
    words = [stemmer.stem(word) for word in words
             if word not in stop_words]
    
    return " ".join(words)

In [9]:
data["clean_questions"] = data["question"].apply(clean_text) # apply clean_question to data)

# Feature Extraction (TfidfVectorizer / TF-IDF)

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [11]:
vectorizer = TfidfVectorizer()

x = vectorizer.fit_transform(data["clean_questions"])
y = data["intent"]

In [12]:
model = LogisticRegression()
model.fit(x, y)

LogisticRegression()

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

In [13]:
import random

def get_response(intent):
    responses = data[data["intent"] == intent]["response"].values
    return random.choice(responses)

In [14]:
data

,question,response,intent,clean_questions
0,Hello,Hello! Welcome to our supermarket. How can I h...,greeting,hello
1,Bye,Thank you for shopping with us. Have a great day!,goodbye,bye
2,Thanks,You're welcome! Happy to help.,thanks,thank
3,Do you have rice?,"Yes, we have different varieties of rice avail...",product_search,rice
4,Is milk available?,"Yes, milk is currently in stock.",product_availability,milk avail
...,...,...,...,...
5995,Show in app category,Displaying in app category,product_category,show app categori
5996,Find for delivery brand,for delivery products available,brand_search,find deliveri brand
5997,Change quantity to for shopping,Quantity updated,quantity_update,chang quantiti shop
5998,Deliver to for groceries,Address updated successfully,address_update,deliv groceri
5999,Payment issue urgent,Please retry payment,payment_issue,payment issu urgent

# chatbot

In [15]:
print("🤝welcom to our chatbot🛒 for your doubt and clarifications❤️")

print("🎉Chatbot ready! Type 'exit' to stop❤️")
while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("🛒Bot: 👋❤️Goodbye!")
        break

    # clean user text
    cleaned = clean_text(user_input)

    # convert to vector
    user_vector = vectorizer.transform([cleaned])

    # predict intent
    predicted_intent = model.predict(user_vector)[0]

    # get response
    reply = get_response(predicted_intent)

    print("🛒Bot:", reply)
print("🎉thank you for your effort😊🌙❤️")

🤝welcom to our chatbot🛒 for your doubt and clarifications❤️
🎉Chatbot ready! Type 'exit' to stop❤️
🛒Bot: eggs removed
🛒Bot: Yes, milk is currently in stock.
🛒Bot: rice removed
🛒Bot: Address updated successfully
🛒Bot: 👋❤️Goodbye!
🎉thank you for your effort😊🌙❤️